#!/bin/bash -f
#*********************************************************************************************************
# Vivado (TM) v2020.1.1 (64-bit)
#
# Filename    : mips_tb.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Simulation script for compiling, elaborating and verifying the project source files.
#               The script will automatically create the design libraries sub-directories in the run
#               directory, add the library logical mappings in the simulator setup file, create default
#               'do/prj' file, execute compilation, elaboration and simulation steps.
#
# Generated by Vivado on Mon Nov 30 13:39:45 +0800 2020
# SW Build 2960000 on Wed Aug  5 22:57:20 MDT 2020
#
# Copyright 1986-2020 Xilinx, Inc. All Rights Reserved. 
#
# usage: mips_tb.sh [-help]
# usage: mips_tb.sh [-lib_map_path]
# usage: mips_tb.sh [-noclean_files]
# usage: mips_tb.sh [-reset_run]
#
#*********************************************************************************************************

# Command line options
xvpath="C:/Xilinx/Vivado/2020.1/bin/"

# Script info
echo -e "mips_tb.sh - Script generated by export_simulation (Vivado v2020.1.1 (64-bit)-id)\n"

# Main steps
run()
{
  check_args $# $1
  setup $1 $2
  compile
  elaborate
  simulate
}

# RUN_STEP: <compile>
compile()
{
  # Compile design files
  ${xvpath}xvlog -prj vlog.prj --nolog
}

# RUN_STEP: <elaborate>
elaborate()
{
  ${xvpath}xelab -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip --snapshot mips_tb xil_defaultlib.mips_tb xil_defaultlib.glbl --nolog
}

# RUN_STEP: <simulate>
simulate()
{
  ${xvpath}xsim mips_tb -key {Behavioral:sim_1:Functional:mips_tb} -tclbatch cmd.tcl -log simulate.log
}

# STEP: setup
setup()
{
  case $1 in
    "-lib_map_path" )
      if [[ ($2 == "") ]]; then
        echo -e "ERROR: Simulation library directory path not specified (type \"./mips_tb.sh -help\" for more information)\n"
        exit 1
      fi
    ;;
    "-reset_run" )
      reset_run
      echo -e "INFO: Simulation run files deleted.\n"
      exit 0
    ;;
    "-noclean_files" )
      # do not remove previous data
    ;;
    * )
  esac

  # Add any setup/initialization commands here:-

  # <user specific commands>

}

# Delete generated data from the previous run
reset_run()
{
  files_to_remove=(xelab.pb xsim.jou xvhdl.log xvlog.log compile.log elaborate.log simulate.log xelab.log xsim.log run.log xvhdl.pb xvlog.pb mips_tb.wdb xsim.dir)
  for (( i=0; i<${#files_to_remove[*]}; i++ )); do
    file="${files_to_remove[i]}"
    if [[ -e $file ]]; then
      rm -rf $file
    fi
  done
}

# Check command line arguments
check_args()
{
  if [[ ($1 == 1 ) && ($2 != "-lib_map_path" && $2 != "-noclean_files" && $2 != "-reset_run" && $2 != "-help" && $2 != "-h") ]]; then
    echo -e "ERROR: Unknown option specified '$2' (type \"./mips_tb.sh -help\" for more information)\n"
    exit 1
  fi

  if [[ ($2 == "-help" || $2 == "-h") ]]; then
    usage
  fi
}

# Script usage
usage()
{
  msg="Usage: mips_tb.sh [-help]\n\
Usage: mips_tb.sh [-lib_map_path]\n\
Usage: mips_tb.sh [-reset_run]\n\
Usage: mips_tb.sh [-noclean_files]\n\n\
[-help] -- Print help information for this script\n\n\
[-lib_map_path <path>] -- Compiled simulation library directory path. The simulation library is compiled\n\
using the compile_simlib tcl command. Please see 'compile_simlib -help' for more information.\n\n\
[-reset_run] -- Recreate simulator setup files and library mappings for a clean run. The generated files\n\
from the previous run will be removed. If you don't want to remove the simulator generated files, use the\n\
-noclean_files switch.\n\n\
[-noclean_files] -- Reset previous run, but do not remove simulator generated files from the previous run.\n\n"
  echo -e $msg
  exit 1
}

# Launch script
run $1 $2
